### ISSUE TITLE
How to generate public private key

### ISSUE THREAD

**Issue by shaffi** [msealand/zmq-zap.node#3]
based on your examples, i am planning to use CURVE mechanism ,i just want know the best approach for generating public/ private key with zeromq

**Comment by erinspice** [comment]
zmq can do this for you. Run `node -e "console.log(require('zmq').curveKeypair())"` to generate Curve keypairs.

**Comment by MaestroJurko** [comment]
How would someone generate a new public key with the same private key / secret??
